### ISSUE TITLE
아이디/비밀번호 찾기 & 비밀번호 변경 기능 추가

### ISSUE THREAD

**Issue by hayeon17kim** [procompiler/developer-village#30]
## Description
![image](https://user-images.githubusercontent.com/50407047/101116963-66baa880-3629-11eb-8273-269027c28360.png)
![image](https://user-images.githubusercontent.com/50407047/101116992-75a15b00-3629-11eb-9910-b29436d24730.png)
![image](https://user-images.githubusercontent.com/50407047/101117011-7d60ff80-3629-11eb-8b55-5f61546ce8e9.png)

비밀번호를 잊었을 때 이메일을 이용해 비밀번호를 찾고, 이를 변경할 수 있는 기능을 추가한다.

## Progress
- [ ] findByEmail 메서드 추가
- [ ] todo
- [ ] todo

**Comment by Jiyoun-Yoo** [comment]
## 아이디 찾기 기능 구현
<img width="1440" alt="스크린샷 2020-12-27 오후 11 44 32" src="https://user-images.githubusercontent.com/68311226/103173308-7bdbcd80-489d-11eb-9f92-98d57ef6dcff.png">

- 기존에는 회원가입을 할 때 전화번호를 받지 않았다. 하지만 아이디 찾기를 할때 입력받을 정보가 이름밖에 없어서, 회원가입시 전화번호를 입력하도록 DB를 수정했다.
- UserMapper.xml에 findID를 추가했다. 회원의 이름과 전화번호를 입력하면 해당 회원의 전화번호를 알 수 있다.
- UserDao와 UserService에 findID와 관련된 메서드를 추가했다.
- /WEB-INF/tiles/appJsp/auth/searchID.jsp를 추가하고 관련된 코드를 작성했다.
- 위의 jsp파일에서 입력 받은 정보를 가지고 회원의 아이디를 찾는다. 그리고 searchIdResult.jsp 파일을 통해 결과를 보여준다.
<img width="1440" alt="스크린샷 2020-12-27 오후 11 45 54" src="https://user-images.githubusercontent.com/68311226/103173333-aaf23f00-489d-11eb-869a-29ecba691316.png">

- 해당 회원의 정보를 찾을 수 없으면 결과를 찾을 수 없다는 화면을 노출한다.
<img width="1440" alt="스크린샷 2020-12-27 오후 11 46 51" src="https://user-images.githubusercontent.com/68311226/103173360-cd845800-489d-11eb-8885-8d1b2fb0b3cf.png">


## Commit
- https://github.com/procompiler/developer-village/commit/a7729c5e24f8bc609572a2745dc4a9f048492b1b
- https://github.com/procompiler/developer-village/commit/6d6a54409533ca6299de335bda30db38599be11c

**Comment by Jiyoun-Yoo** [comment]
## 비밀번호 찾기 기능
- UserMapper.xml에 findPwd를 추가했다.
- 아이디 찾기와 동일한 방법으로 진행했다.
<img width="1440" alt="스크린샷 2020-12-27 오후 11 49 21" src="https://user-images.githubusercontent.com/68311226/103173405-2653f080-489e-11eb-9d11-44b60ba2614b.png">
<img width="1440" alt="스크린샷 2020-12-27 오후 11 50 03" src="https://user-images.githubusercontent.com/68311226/103173426-3ec40b00-489e-11eb-873f-fb3611a26454.png">
<img width="1440" alt="스크린샷 2020-12-27 오후 11 50 33" src="https://user-images.githubusercontent.com/68311226/103173439-500d1780-489e-11eb-98d5-3d052e3c67f4.png">

## Commit
- https://github.com/procompiler/developer-village/commit/a7729c5e24f8bc609572a2745dc4a9f048492b1b
- https://github.com/procompiler/developer-village/commit/6d6a54409533ca6299de335bda30db38599be11c

## 추후 보완할 것
- 비밀번호를 암호화하여 저장했기 때문에, 바로 노출하지 않고 등록된 이메일로 임시 비밀번호를 전송하는 방식으로 전환하면 좋을 것 같다.
- 화면 하나하나에 대한 jsp파일을 만들지 않고 진행할 수 있다면, 그런 방식으로 수정한다.

**Comment by Jiyoun-Yoo** [comment]
## 비밀번호 변경 기능
- 입력한 정보와 일치하는 결과를 찾을 수 없을 때는 회원 정보를 찾을 수 없다는 화면을 노출한다.
- 이 경우에는 회원 번호를 -1로 리턴하도록 하였다.
<img width="1440" alt="스크린샷 2020-12-29 오전 1 26 04" src="https://user-images.githubusercontent.com/68311226/103228729-d431ce80-4974-11eb-9c05-1339b8668e12.png">

- 입력한 정보와 일치하는 결과를 찾으면, 비밀번호를 재설정할 수 있도록 한다.
- 이 경우에는 회원 번호를 리턴하고, 이에 맞춰 비밀번호를 수정할 수 있도록 코드를 작성하였다.
<img width="1440" alt="스크린샷 2020-12-29 오전 1 27 44" src="https://user-images.githubusercontent.com/68311226/103228835-0f340200-4975-11eb-8bfa-78bed9c1a2ed.png">

## Commit
- https://github.com/procompiler/developer-village/commit/c2a6dc4d8486b2f2ba5002e8354abf035cb28c27

## 추후 보완할 것
- 비밀번호 입력 후 재입력을 받아 서로 일치하면 비밀번호가 변경되도록 수정한다.
- 비밀번호 변경시 유저의 아이디를 받아, 일치하면 번호가 변경되도록 수정한다.
- 현재는 유저의 번호가 URL에 노출되는데, 노출되지 않도록 수정한다.

## 의문점
- 회원이 입력한 이메일, 전화번호, 이름을 가지고 회원을 검색한 후 새 비밀번호를 설정하는 과정에서 입력한 비밀번호를 넘겨받을 메서드를 AuthController.java에 작성하였다. 하지만 아래와 같이 작성한 경우 Controller에서 데이터를 가져오지 못했다. 값을 가져가지 못했을 뿐만 아니라, 아예 Controller가 실행되지 않았다.

`searchPwdResult.jsp`
```jsp
      <form id="updatePwd" action="updatePwd" method="post">
        <input id='userNo' type='hidden' name='userNo' value='${param.userNo}'>
        <div class="mb-3 row">
          <label for="password" class='form-label col-sm-2 col-form-label'>비밀번호</label>
          <div class="col-sm-10">
            <input id='inputPassword' type='password' class="form-control" name='password' placeholder="password">
          </div>
        </div>

        <div class="d-grid gap-2">
          <button class="btn btn-primary">비밀번호 재설정</button>
        </div>
      </form>
```

`AuthController.java`
```java
  @PostMapping("updatePwd")
  public void updatePwd(int userNo, String password) throws Exception {
    userService.updatePwd(userNo, password);
  }

```

- 하지만 아래와 같이 수정한 후에는 코드가 원하는대로 작동했다. 왜 이런 방식으로 코드를 작성해야 하는지 알아봐야 한다.

`searchPwdResult.jsp`
```jsp
      <form id="updatePwd" action="searchPwdResult-send" method="post">
        <input id='userNo' type='hidden' name='userNo' value='${param.userNo}'>
        <div class="mb-3 row">
          <label for="password" class='form-label col-sm-2 col-form-label'>비밀번호</label>
          <div class="col-sm-10">
            <input id='inputPassword' type='password' class="form-control" name='password' placeholder="password">
          </div>
        </div>

        <div class="d-grid gap-2">
          <button class="btn btn-primary">비밀번호 재설정</button>
        </div>
      </form>
```

`AuthController.java`
```java
  @PostMapping("searchPwdResult-send")
  public void searchPwdResult(int userNo, String password) throws Exception {
    userService.updatePwd(userNo, password);
    return "redirect:login";
  }
```

**Comment by Jiyoun-Yoo** [comment]
- /auth/updatePwd에 접근할 수 없었던 이유는, AuthInterCeptor때문이었다.

**Comment by Jiyoun-Yoo** [comment]
## 수정사항
- 비밀번호 찾기 후 비밀번호를 재설정할 때, 비밀번호를 두 번 입력해야 하고 이 두 비밀번호가 일치해야 비밀번호가 수정되도록 했다.
<img width="1440" alt="스크린샷 2020-12-29 오후 11 51 21" src="https://user-images.githubusercontent.com/68311226/103292228-c2156600-4a30-11eb-8720-c1b4e7decdd8.png">

```jsp
      <form id="updatePwdForm" action="updatePwd" method="post">
        <input id='userNo' type='hidden' name='userNo' value='${param.userNo}'>
        <div class="mb-3 row">
          <label for="password" class='form-label col-sm-2 col-form-label'>비밀번호</label>
          <div class="col-sm-10">
            <input id='inputPassword' type='password' class="form-control" name='password' placeholder="password">
          </div>
        </div>
    
		    <div class="mb-3 row">
		      <label for="passwordConfirm" class='form-label col-sm-2 col-form-label'>비밀번호 확인</label>
		        <div class="col-sm-10">
		          <input id="passwordConfirm" type='password' class="form-control" name='passwordConfirm' 
		                 placeholder="위의 비밀번호와 동일하게 입력">
		        </div>
		    </div>
		    
        <div class="d-grid gap-2">
          <button class="btn btn-primary">비밀번호 재설정</button>
        </div>
      </form>


<script>
document.querySelector("#updatePwdForm").onsubmit = () => {
  var inputPassword = document.querySelector("#inputPassword");
  var passwordConfirm = document.querySelector("#passwordConfirm");

  if (inputPassword.value.length < 8) {
    alert("비밀번호를 8자 이상 입력하세요!");
    return false;
  } else if (inputPassword.value != passwordConfirm.value) {
    alert("비밀번호가 일치하지 않습니다.");
    return false;
  }
};
</script>
```
