### ISSUE TITLE
JSP + EL + JSTL로 전환

### ISSUE THREAD

**Issue by hayeon17kim** [procompiler/developer-village#38]
## Description
현재 JSP 파일에 자바 코드가 그대로 들어 있다.

## Solution
- jsp 코드에 el + JSTL 문법을 적용한다.
- detail의 경우 예외 처리를 Servlet에 맡긴다.

## Progress
- [x] article 
  - [x] list
  - [x] detail
- [ ] user
  - [ ] list
  - [x] detail
- [ ] block
  - [ ] list
  - [ ] detail
- [x] mypage
  - [x] taglist
  - [x] userlist
  - [ ] info
- [x] comment
  - [x] list
- [x] badge
  - [x] list
  - [x] detail
- [ ] tag
  - [ ] list
  - [ ] detail
- [ ] header

**Comment by Jiyoun-Yoo** [comment]
- /article/list.jsp와 /article/detail.jsp의 경우 tag의 색상 불러오지 못함, 관련하여 더 알아보고 추가 보완할 예정.
- 게시판을 나눈 이후로 게시글을 키워드로 검색하는 것이 불가해진 것으로 판단되어 버그 수정 예정, 이후 /article/list.jsp 파일에서 관련 코드 수정 예정

**Comment by Jiyoun-Yoo** [comment]
- tag의 색상 및 글꼴의 색상 불러오는 문제 해결

**Comment by Jiyoun-Yoo** [comment]
- 게시글 검색 기능 수정 및 보완 완료
