### ISSUE TITLE
Servlet을 Spring MVC규칙에 따라 Controller로 변경한다.

### ISSUE THREAD

**Issue by parkminseob** [procompiler/developer-village#50]
## Description
Spring webMVC규칙에 따라 Servlet들을 Controller로 리팩토링한다.

## Progress
- [x] ArticleController
- [x] CommentController
- [x] TagController
- [x] BookmarkController
- [x] BlockController
- [x] BadgeController
- [x] CommunitController
- [x] UserController
- [x] ReportController

**Comment by Jiyoun-Yoo** [comment]
- ArticleController, CommentController, TagController로 변경 후 CRUD 테스트 완료
- /article/update의 경우 기존에 선택된 태그를 포함하여 새로운 태그를 선택하고 수정을 누르면 수정이 되지 않는 문제 발생 -> 해결 예정

**Comment by parkminseob** [comment]
- [x]  UserController의 detail메서드가 제대로 실행되지 않는 문제 발생 -> 해결
