### ISSUE TITLE
bug : ArticleMapper.xml

### ISSUE THREAD

**Issue by cchoijjinyoung** [procompiler/developer-village#8]
- [x] ArticleMapper.xml 파일 illegalStateException: Type handler was null on parameter mapping for property writer

**Comment by hayeon17kim** [comment]
에러메시지: java.lang.IllegalStateException: Type handler was null on parameter mapping for property 
Article의 writer 필드 타입을 int에서 User로 바꾼 후에도 `insert` 태그의 sql문을 `#{writer}`를 `#{writer.no}`로 변경하지 않아서 발생한 문제입니다. 해당 부분을 수정하였더니 정상적으로 서버가 실행되었습니다.
